// Generated by CoffeeScript 1.3.3
(function() {
  var vein;

  vein = Vein.create();

  vein.on('ready', function(services) {
    console.log("Connected - Available services: " + services);
    return vein.add(1, 2, 3, 4, function(res) {
      return console.log(res);
    });
  });

}).call(this);
